#!/usr/bin/env bash
# install and configure a response page for nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
