#!/usr/bin/env bash
# install and configure HAProxy
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.4 -y
apt-get -y install haproxy=2.4.\*
echo "Enabled=1" >> /etc/default/haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
cat << EOF >> /etc/haproxy/haproxy.cfg
frontend
	bind :80
	default_backend my_web_servers

backend
	balance roundrobin
	server 6700-web-01 54.160.79.143
	server 6700-web-02 18.233.65.33
EOF

service haproxy restart
