#!/usr/bin/env bash
# creating a mysql dump for backup and archiving it with date as name
ZIP_FILE=$(date +%d-%m-%Y)
EXT='tar.gz'
mysqldump --all-databases -u root --password="$1" > backup.sql 2>/dev/null
tar -czvf "$ZIP_FILE.$EXT" backup.sql
