#!/usr/bin/env bash
# removing the bug(interference) and restarting nginx
rm /etc/nginx/sites-enabled/default
ln -n /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
